import os
import json
import shutil
from pathlib import Path

from unidiff import PatchSet

from typing import Optional
from enum import Enum
import hashlib
from tree_sitter_language_pack import get_parser
from tree_sitter import Node
from collections import defaultdict

from git import Repo, GitCommandError
from milo.codesift.repograph import create_repograph
from milo.codesift.repobrowser import load_repo_graph
from milo.agents.codereview import get_agent as get_codereview_agent
from milo.codesift.parsers.utils import (get_file_extension, get_programming_language, guess_extension_from_shebang)
from milo.codesift.parsers import supported_languages, Treesitter
from milo.codereview.models import InputCode, ReviewListModel
import traceback
import re

from milo.codesift.parsers import Language



def load_review_cache(path: Path) -> dict:
    """
    Loads the review cache from a JSON file at the specified path.

    If the file exists, opens the file and loads contents into a dictionary using json.load().
    If the file does not exist, returns a default structure containing:
        - 'hunks_reviewed': Dictionary to track code hunk review status by SHA/hunk index
        - 'head_shas': List of commit head SHAs for tracking review context

    This function initializes the review state tracking mechanism used across the code analysis pipeline.
    The returned cache is consumed by functions like:
        - apply_code_reviews()
        - generate_diff_stats()
        - update_review_status()
    ...and others in the analysis workflow (see callers in codebase).

    The cache structure serves as a persistent state store between operations, enabling:
    - Incremental review tracking across sessions
    - Commit history correlation with review decisions
    - Diff context preservation for reporting

    Parameters:
        path (Path): Filesystem path to JSON file containing review cache data

    Returns:
        dict: Loaded review cache data or default structure if file doesn't exist

    Raises:
        json.JSONDecodeError: If existing file contains invalid JSON
        OSError: If file exists but cannot be accessed
    """
    if path.exists():
        with path.open() as f:
            return json.load(f)
    return {"hunks_reviewed": {}, "head_shas": []}


def save_review_cache(path: Path, data: dict) -> None:
    """
    Save the review cache to a JSON file with structured formatting.

    This function serializes and persists a dictionary-based review cache structure
    to disk using two-space indentation for human readability. The implementation
    ensures atomic writes by using the Pathlib open() context manager.

    Args:
        path (Path): Target file path for cache storage. Expected to have .json extension
                        but not enforced at runtime. The directory must exist.
        data (dict): Review metadata containing at least 'timestamp', 'author', and
                        'diff_hashes' keys as generated by load_review_cache()

    Raises:
        OSError: If directory in path doesn't exist or file can't be written
        TypeError: If data contains non-serializable values
        ValueError: If data is empty or has invalid structure

    Note:
        This function is called after processing git diff outputs and before rendering
        UI components. The 'diff_hashes' key stores SHA-1 hashes of reviewed code blocks.
        Used in conjunction with load_review_cache() for state persistence across sessions.
    """
    with path.open("w") as f:
        json.dump(data, f, indent=2)


def hash_hunk(file_path: str, hunk_text: str) -> str:
    """
    Compute a SHA-1 hash of the combination of a file path and a text hunk.

    This method concatenates the given file path with the provided text hunk,
    separated by a newline character. The combined string is then encoded in UTF-8
    and hashed using the SHA-1 algorithm. The resulting hash is returned as a hexadecimal
    string representation.

    The newline separator ensures unique context boundaries between file metadata
    (path) and content (hunk). UTF-8 encoding handles non-ASCII characters consistently.
    Used in version tracking systems to uniquely identify code changes.

    Args:
        file_path (str): The path to the file that contains the hunk.
        hunk_text (str): The text content of the hunk to be hashed.

    Returns:
        str: A hexadecimal string representing the SHA-1 hash of the concatenated
                and encoded file path and hunk text.

    Example:
        >>> hash_hunk("example.txt", "This is a sample hunk\nwith two lines.")
        'a7c3e1b8d6f904c8a2e5b1d7c6f8e9a0b1c2d3e4f'

    Note:
        SHA-1 is used for compatibility with legacy systems. For cryptographic use,
        consider stronger hash functions like SHA-256.
    """
    return hashlib.sha1((file_path + "\n" + hunk_text).encode("utf-8")).hexdigest()


def format_hunk_with_line_numbers(hunk) -> str:
    """
    Formats a hunk of code changes into a unified diff-style string with line numbers and change indicators.

    This function is typically used in version control or code comparison systems to visualize differences between code versions.
    Each line in the hunk is annotated with: 
        - Right-aligned 4-digit line number (from target/source context)
        - Change indicator: '+' for additions, '-' for removals, ' ' for context lines
        - Original code line value

    Args:
        hunk (list): List of Line objects representing individual code changes. Each object must expose:
                    `is_added`, `is_removed`, `is_context`, `target_line_no`, `source_line_no`, and `value` attributes.

    Returns:
        str: Concatenated string of formatted lines. No newline characters are explicitly added between lines;
                assumes line.value already contains newlines where appropriate.

    Behavior Details:
        - For context lines, prioritizes target_line_no when available, otherwise falls back to source_line_no
        - Edge cases with missing line numbers default to 0 (e.g., hunk boundaries)
        - Debug print statement (commented) remains for development visibility

    Integration Context:
        - Output format aligns with standard unified diff visualization patterns
        - Typically precedes final diff rendering or serialization operations
        - Used by `render_diff_view()` and `serialize_hunk()` in the same module for UI/CLI presentation

    Example Usage:
        >>> hunk = [Line(is_added=True, target_line_no=42, value="print('new code')\n")]
        >>> format_hunk_with_line_numbers(hunk)
        '  42 + print('new code')\n'
    """
    lines = []
    for line in hunk:
        # print(line)
        if line.is_added:
            prefix = "+"
            line_no = line.target_line_no
        elif line.is_removed:
            prefix = "-"
            line_no = line.source_line_no
        elif line.is_context:
            prefix = " "
            line_no = line.target_line_no or line.source_line_no
        else:
            prefix = " "
            line_no = line.target_line_no or line.source_line_no or 0  # Edge case
        lines.append(f"{line_no:4} {prefix} {line.value}")
    return "".join(lines)


def extract_function_ranges(tree) -> list:
    """
    Iterates over a Tree-sitter parse tree to extract function definition ranges.
    
    Args:
        tree: Tree-sitter syntax tree object containing root_node with parsed code.
    
    Returns:
        List of tuples in format (start_line, end_line, node) where lines are 1-based indices,
        filtered to only include nodes of type 'function_definition'.
    
    Used by review_merge_request() to identify function boundaries in source code during
    GitLab MR analysis. The +1 offset compensates for Tree-sitter's 0-based line numbering.
    """
    return [
        (node.start_point[0] + 1, node.end_point[0] + 1, node)
        for node in tree.root_node.children
        if node.type == "function_definition"
    ]


def extract_function_name(node: Node) -> Optional[str]:
    # Walk down to the declarator or identifier
    """
    Extract the function name from Tree-sitter nodes representing function definitions or declarators.
    
    Handles `function_definition`, `function_declarator`, and nested `declarator` node types by
    traversing the AST structure to locate the identifier node. Returns None when no valid identifier
    is found in the node hierarchy.
    
    Args:
        node (Node): Tree-sitter node to extract name from. Expected to be a function_definition,
                      function_declarator, or declarator node type.
    
    Returns:
        Optional[str]: Decoded identifier text if found, otherwise None.
    
    This function is primarily used in C/C++/C# parser components to normalize function declarations
    across different AST structures. Handles recursive nested declarators and ensures compatibility
    with both definition and declaration node types in the Tree-sitter grammar.
    """
    if node.type == "function_definition":
        declarator = next(
            (child for child in node.children if child.type == "declarator"), None
        )
        if declarator:
            return extract_function_name(declarator)

    if node.type in {"function_declarator", "declarator"}:
        identifier = next(
            (child for child in node.children if child.type == "identifier"), None
        )
        if identifier:
            return identifier.text.decode()

    return None


def map_changed_lines_to_function(old_lines, new_lines, old_fn_ranges, new_fn_ranges):
    """
    Maps modified line numbers to their corresponding function definition in either new/old code versions.

    This function prioritizes matching changed lines against new code function ranges first. If no match is found,
    it falls back to checking old code function ranges. Used for tracking which functions are affected by code changes
    during version comparisons (e.g., in diff analysis). The implementation leverages AST nodes to preserve structural metadata.

    Args:
        old_lines (List[int]): Line numbers modified in the original code version
        new_lines (List[int]): Line numbers modified in the updated code version
        old_fn_ranges (Optional[List[Tuple[int, int, ast.AST]]]): Function ranges from original code (start_line, end_line, node)
        new_fn_ranges (List[Tuple[int, int, ast.AST]]): Function ranges from updated code (start_line, end_line, node)

    Returns:
        Optional[Dict]: Mapping information containing:
            - 'from' (str): 'new'|'old' indicating which version matched
            - 'start' (int): Start line number of the function
            - 'end' (int): End line number of the function
            - 'name' (str): Function name extracted via extract_function_name()
            - 'node' (ast.AST): Original AST node representing the function
        Returns None if no matching function is found

    Note:
        Requires extract_function_name() to resolve AST node names. Used by code diff analysis tools to correlate 
        line-level changes with semantic function boundaries.
    """
    for start, end, node in new_fn_ranges:
        if any(start <= line <= end for line in new_lines if line is not None):
            # print("Found mapping in new code")
            return {
                "from": "new",
                "start": start,
                "end": end,
                "name": extract_function_name(node),
                "node": node,
            }

    # Fallback: try old version
    if old_fn_ranges is not None:
        for start, end, node in old_fn_ranges:
            if any(start <= line <= end for line in old_lines if line is not None):
                # print("Found mapping in old code")
                return {
                    "from": "old",
                    "start": start,
                    "end": end,
                    "name": extract_function_name(node),
                    "node": node,
                }

    return None


def map_hunk_to_function(hunk, old_ranges, new_ranges):
    """
    Map a diff hunk to the AST function node it belongs to by analyzing modified/added lines.

    This function determines which function definition (from old/new code ranges) contains 
    the changes represented by the hunk. It prioritizes new_ranges (post-diff changes) over 
    old_ranges (pre-diff changes) when resolving line range overlaps.

    Args:
        hunk: Diff hunk object with source_start/target_start and iterable of line objects
            (each line has a line_type attribute: '+' for additions, '-' for deletions)
        old_ranges: List of tuples (start_line, end_line, ast_node) representing original
            function definitions in the pre-diff code
        new_ranges: List of tuples (start_line, end_line, ast_node) representing updated
            function definitions in the post-diff code

    Returns:
        The AST node corresponding to the function containing the hunk, or None if no match

    Process:
        1. Extracts line numbers of added/modified lines from hunk.target_start
        2. Extracts line numbers of removed lines from hunk.source_start
        3. Matches these line sets against new_ranges and old_ranges in sequence

    Note:
        Debug prints are temporary for tracking matching behavior during development
        Commented-out line_type == ' ' handling indicates potential future support for context lines
    """
    print(hunk)
    changed_lines_new = {
        hunk.target_start + i
        for i, line in enumerate(hunk)
        if line.line_type == "+"  # or line.line_type == " "
    }
    changed_lines_old = {
        hunk.source_start + i
        for i, line in enumerate(hunk)
        if line.line_type == "-"  # or line.line_type == " "
    }

    def match_in_ranges(lines, ranges):
        for start, end, node in ranges:
            if any(start <= line <= end for line in lines):
                return node
        return None

    matched_node = match_in_ranges(changed_lines_new, new_ranges)
    print("matched in new")
    print(matched_node)
    if not matched_node:
        matched_node = match_in_ranges(changed_lines_old, old_ranges)
        print("matched in old")
        print(matched_node)
    return matched_node

def review_path(repo_root, paths: list[str], repo_name = None) -> list[str]:
    """
    Takes a list of file and directory paths, and returns a list of all files
    with supported extensions (.c, .h, .py). This function recursively walks
    through directories to find all supported files.
    
    TODO: Use GitPython to respect .gitignore files.
    """
    files_to_review = set()
    
    for path_str in paths:
        path = Path(path_str).resolve()
        if not path.exists():
            continue

        if path.is_file():
            file_extension = get_file_extension(str(path))
            if len(file_extension) == 0:
                file_extension = guess_extension_from_shebang(file_path=str(path))
            programming_language = get_programming_language(file_extension)
            if programming_language.value in supported_languages():
                files_to_review.add(str(path))
        elif path.is_dir():
            for root, _, files in os.walk(path):
                for file in files:
                    file_path = Path(root) / file
                    file_extension = get_file_extension(str(file_path))
                    if len(file_extension) == 0:
                        file_extension = guess_extension_from_shebang(file_path=str(file_path))
                    programming_language = get_programming_language(file_extension)
                    if programming_language.value in supported_languages():
                        files_to_review.add(str(file_path))

    # Generate a repograph of the repository
    repomap_path = os.path.join(repo_root, '.milo')
    Path(repomap_path).mkdir(exist_ok=True)
    create_repograph(root = str(repo_root),
                     save_path=repomap_path)
    
    # Filter list by excluding patterns from .gitignore

    #Invoke the master Code Review Agent
    agent = get_codereview_agent(metadata_path=os.path.join(repomap_path, "metadata.json"), repo_path=repo_root, repo_name=repo_name)

    for local_path in files_to_review:
        # Guess the programming language
        file_extension = get_file_extension(local_path)
        if len(file_extension) == 0:
            file_extension = guess_extension_from_shebang(file_path=local_path)
        programming_language = get_programming_language(file_extension)

        if programming_language.value not in supported_languages():
            print("Language parsing currently not supported")
            continue
        
        file_content = None
        try:
            print(f"Processing {local_path}")
            with open(local_path, "r") as file:
                # Read the entire content of the file into a string
                file_content = file.read().encode()

                # Parse the file using treesitter, and extract the elements from the code
                treesitter_parser = Treesitter.create_treesitter(programming_language)
                #treesitter_nodes = treesitter_parser.parse(file_content)
                treesitter_parser.parse(file_content)
                treesitter_nodes = treesitter_parser.iterate_blocks()
                for node in treesitter_nodes:
                    method_name = node.name
                    method_comment = None

                    method_source_code = node.method_source_code
                    if node.doc_comment and node.doc_comment not in node.method_source_code:
                        method_comment = node.doc_comment
                    try:
                        # Invoke the agent to do a code review and collect the review to a JSON file
                        user_prompt = InputCode(language = programming_language.value, 
                                                method=method_source_code, 
                                                docstring = method_comment or "")
                        agent.clear_history()
                        response = agent.call(user_prompt.model_dump_json())
                        response_json = json.loads(response)
                        reviews = ReviewListModel.validate_python(
                                    response_json if isinstance(response_json, list) else []
                                )
                        print(reviews)
                    except:
                        print("Error processing node. Skip")
                        traceback.print_exc()
        except FileNotFoundError:
            print(f"{local_path} No longer exists.")

    return sorted(list(files_to_review))

def review_git_changes(repo_path):
    pass